### ISSUE TITLE
Masking in adjacency matrix

### ISSUE THREAD

**Issue by Mugariya** [weiba/MTGCN#1]
Hello,

How did you include masks in the adjacency matrix for CPDB pickle file? Is there a method you follow for the values of mask_te, mask, y and y_te?

**Comment by weiba** [comment]
There are limited labelled gene data (796 positive and 2187 negative samples). We only use the labelled data to optimize and test our model. Hence we use a mask list with the gene size length. The values in the mask are true, corresponding to the positive or negative samples. Otherwise, the values in the mask were false. We downloaded the mask from the data of the EMOGI method directly. mask_te and mask_ tr were two lists where values were true if the corresponding samples were in the testing or training set. We build the mask_te and mask_ tr by randomly five-fold division. y represents the labels of all genes, with positive sample values of 1 and the rest of 0. y_te is the mask of the y, whose value is true if the y's value is 1. Otherwise, the value of the y_te is false if the corresponding value of the y is 0.

**Comment by Mugariya** [comment]
Is it possible to give me the access to that data?

Thanks

**Comment by Mugariya** [comment]
Because if I use some other data, then I need to create the masks differently? And they won't match the masks that you have.

**Comment by weiba** [comment]
The “mask_all.pkl ” under the data folder is the mask file.  I think you should create a different masks for new data. Beacause the mask file contains the number of  genes involved in your work.

**Comment by Mugariya** [comment]
Yes True. Thank you
